apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: cpu-inference-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-nodepool: cpu-inference-pool
  nodeTaints:
  - key: inference
    value: "true"
    effect: NoSchedule
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: gpu-inference-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-nodepool: gpu-pool
  nodeTaints:
  - key: inference
    value: "true"
    effect: NoSchedule
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: video-flavor
spec:
  nodeLabels:
    cloud.google.com/gke-nodepool: video-pool
  nodeTaints:
  - key: inference
    value: "true"
    effect: NoSchedule
