# do a k8 inference deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benzaiten-inference-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: benzaiten-inference
  template:
    metadata:
      labels:
        app: benzaiten-inference
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: cpu-inference-pool
        # cloud.google.com/gke-nodepool: gpu-pool

      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"

      containers:
      - name: benzaiten-inference-container
        image: northamerica-northeast2-docker.pkg.dev/project-0c6e9a84-c914-4d2f-ace/benzaiten/benzaiten-inference:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
        #gpu-pool:
          # requests:
          #   memory: "8Gi"
          #   cpu: "2"
          # limits:
          #   nvidia.com/gpu: 1
          #   memory: "16Gi"
          #   cpu: "4"

        #cpu-inference-pool:
        resources:
          requests:
            cpu: "4"
            memory: "12Gi"
          limits:
            cpu: "6"
            memory: "24Gi"