# this file serves as the full automated test workflow CI combining all elementary CIs for QA + validation
name: QA & Validation Automated Test CI

on:
    push:
        branches: [ "main", "model-orchestration" ]
        paths:
            - "Dockerfile"
            - ".dockerignore"
            - "backend/**"
            - "requirements.txt"
            - "backend/scripts/benzaiten_inference/k8s/**"
            - "**/*.sh"
            - ".github/workflows/*.yml"
    pull_request:
        branches: [ "main", "model-orchestration" ]
        paths:
            - "Dockerfile"
            - ".dockerignore"
            - "backend/**"
            - "requirements.txt"
            - "backend/scripts/benzaiten_inference/k8s/**"
            - "**/*.sh"
            - ".github/workflows/*.yml"

jobs:
    python-ci:
        uses: ./.github/workflows/python-ci.yml
    
    docker-build:
        uses: ./.github/workflows/docker-build.yml

    k8s-manifest-check:
        uses: ./.github/workflows/k8s-manifest-check.yml
    
    sh-script-check:
        uses: ./.github/workflows/sh-script-check.yml