name: Kubernetes Manifest Check

on:
    workflow_call:

jobs:
    k8s-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Validate Kubernetes manifests client-side
          run: |
            kubectl create --dry-run=client --validate=false -f backend/scripts/benzaiten_inference/k8s/backend-rbac.yaml
            kubectl create --dry-run=client --validate=false -f backend/scripts/benzaiten_inference/k8s/backend-deployment.yaml
            kubectl create --dry-run=client --validate=false -f backend/scripts/benzaiten_inference/k8s/service.yaml