name: Kubernetes Manifest Check

on:
    workflow_call:

jobs:
    k8s-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Validate Kubernetes manifests client-side
          run: |
            shopt -s nullglob
            kubectl apply \
                --dry-run=client \
                -f backend/scripts/benzaiten_inference/k8s/*.yaml